version: "3.8"

services:
  # API service
  api:
    build:
      context: ./api
    ports:
      - "5050:5050"
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app

  # Frontend service
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    # environment:
    #   - VITE_FLASK_APP_API_URL=http://api:5050/
    depends_on:
      - api
    volumes:
      - /app/node_modules
      - ./frontend/:/app
  #New MongoDB service
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017 # Map host port 27017 to container port 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
      # MONGO_INITDB_DATABASE: images
    volumes:
      - mongo-data:/data/db # Create a named volume to persist data

  # New Mongo-Express service
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081 # Map host port 8081 to container port 8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo # Use the service name to connect to the MongoDB container
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      # ME_CONFIG_MONGODB_URL: mongodb://root:very-strong-db-password@mongo:27017/images-gallery?authSource=admin # Use the service name to connect to the MongoDB container
    depends_on:
      - mongo # Wait for MongoDB to start before starting Mongo-Express

volumes:
  mongo-data:
  node_modules:
