version: "3.8"

services:
  # API service
  api:
    build:
      context: ./api
    ports:
      - "5050:5050"
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app

  # Frontend service
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    # environment:
    #   - VITE_FLASK_APP_API_URL=http://api:5050/
    depends_on:
      - api
    volumes:
      - /app/node_modules
      # - //wsl.localhost/Ubuntu/home/chrismo/documents/projects/python/flask/images-gallery/frontend:/app
      - ./frontend/:/app
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: db_images_gallery
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: moreira.christophe@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
