version: "3.8"

services:
  # API service
  api:
    build:
      context: ./api
    ports:
      - "5050:5050"
    env_file:
      - ./api/.env

  # Frontend service
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    # environment:
    #   - VITE_FLASK_APP_API_URL=http://api:5050/
    depends_on:
      - api
